sudo: required
services:
  - docker

before_install:
  - docker build -t ahmadazadzadeh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ahmadazadzadeh/react-test npm test -- --coverage

after_success:
  - docker build -t ahmadazadzadeh/multi-client ./client
  - docker build -t ahmadazadzadeh/multi-nginx ./nginx
  - docker build -t ahmadazadzadeh/multi-server ./server
  - docker build -t ahmadazadzadeh/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push ahmadazadzadeh/multi-client
  - docker push ahmadazadzadeh/multi-nginx
  - docker push ahmadazadzadeh/multi-server
  - docker push ahmadazadzadeh/multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-container-docker
  env: MultiContainerDocker
  bucket_name: elasticbeanstalk-us-west-1-306476627547
  bucket_path: docker-container-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY